/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */

package ti.sentry

import io.sentry.Sentry
import org.appcelerator.kroll.KrollModule
import org.appcelerator.kroll.annotations.Kroll

@Kroll.module(name = "TitaniumSentry", id = "ti.sentry")
class TitaniumSentryModule: KrollModule() {

	// Methods

	@Kroll.method
	fun captureMessage(message: String) {
		Sentry.captureMessage(message)
	}
}
